version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: ./gradlew -q properties
      - run: ./gradlew -q dependencies
      - run: ./gradlew --full-stacktrace check